# Generated by Django 4.2.5 on 2023-09-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("Result_1", models.CharField(max_length=32, verbose_name="第一题")),
                ("Result_2", models.CharField(max_length=32, verbose_name="第二题")),
                ("Result_3", models.CharField(max_length=32, verbose_name="第三题")),
                ("Result_4", models.CharField(max_length=32, verbose_name="第四题")),
                ("Result_5", models.CharField(max_length=32, verbose_name="第五题")),
                ("Result_6", models.CharField(max_length=32, verbose_name="第六题")),
                ("Result_7", models.CharField(max_length=32, verbose_name="第七题")),
                ("Result_8", models.CharField(max_length=32, verbose_name="第八题")),
                ("Result_9", models.CharField(max_length=32, verbose_name="第九题")),
                ("Result_10", models.CharField(max_length=32, verbose_name="第十题")),
                ("Result_A", models.CharField(max_length=1024, verbose_name="第十一题")),
                ("Result_B", models.CharField(max_length=1024, verbose_name="第十二题")),
                (
                    "Score_obj_all",
                    models.CharField(max_length=32, verbose_name="客观题总分"),
                ),
                (
                    "Score_sub_all",
                    models.CharField(max_length=32, verbose_name="主观题总分"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionObj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Question_1",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第一题"
                    ),
                ),
                (
                    "Question_2",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第二题"
                    ),
                ),
                (
                    "Question_3",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第三题"
                    ),
                ),
                (
                    "Question_4",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第四题"
                    ),
                ),
                (
                    "Question_5",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第五题"
                    ),
                ),
                (
                    "Question_6",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第六题"
                    ),
                ),
                (
                    "Question_6_A",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第六题A选项"
                    ),
                ),
                (
                    "Question_6_B",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第六题B选项"
                    ),
                ),
                (
                    "Question_6_C",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第六题C选项"
                    ),
                ),
                (
                    "Question_6_D",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第六题D选项"
                    ),
                ),
                (
                    "Question_7",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第七题"
                    ),
                ),
                (
                    "Question_7_A",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第七题A选项"
                    ),
                ),
                (
                    "Question_7_B",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第七题B选项"
                    ),
                ),
                (
                    "Question_7_C",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第七题C选项"
                    ),
                ),
                (
                    "Question_7_D",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第七题D选项"
                    ),
                ),
                (
                    "Question_8",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第八题"
                    ),
                ),
                (
                    "Question_8_A",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第八题A选项"
                    ),
                ),
                (
                    "Question_8_B",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第八题B选项"
                    ),
                ),
                (
                    "Question_8_C",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第八题C选项"
                    ),
                ),
                (
                    "Question_8_D",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第八题D选项"
                    ),
                ),
                (
                    "Question_9",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第九题"
                    ),
                ),
                (
                    "Question_9_A",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第九题A选项"
                    ),
                ),
                (
                    "Question_9_B",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第九题B选项"
                    ),
                ),
                (
                    "Question_9_C",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第九题C选项"
                    ),
                ),
                (
                    "Question_9_D",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第九题D选项"
                    ),
                ),
                (
                    "Question_10",
                    models.CharField(
                        default="题目测试", max_length=512, verbose_name="第十题"
                    ),
                ),
                (
                    "Question_10_A",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第十题A选项"
                    ),
                ),
                (
                    "Question_10_B",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第十题B选项"
                    ),
                ),
                (
                    "Question_10_C",
                    models.CharField(
                        default="选项测试", max_length=256, verbose_name="第十题C选项"
                    ),
                ),
                (
                    "Question_10_D",
                    models.CharField(
                        default="选项测试", max_length=512, verbose_name="第十题D选项"
                    ),
                ),
                ("ans_1", models.CharField(max_length=32, verbose_name="第一题答案")),
                ("ans_2", models.CharField(max_length=32, verbose_name="第二题答案")),
                ("ans_3", models.CharField(max_length=32, verbose_name="第三题答案")),
                ("ans_4", models.CharField(max_length=32, verbose_name="第四题答案")),
                ("ans_5", models.CharField(max_length=32, verbose_name="第五题答案")),
                ("ans_6", models.CharField(max_length=32, verbose_name="第六题答案")),
                ("ans_7", models.CharField(max_length=32, verbose_name="第七题答案")),
                ("ans_8", models.CharField(max_length=32, verbose_name="第八题答案")),
                ("ans_9", models.CharField(max_length=32, verbose_name="第九题答案")),
                ("ans_10", models.CharField(max_length=32, verbose_name="第十题答案")),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Question_A", models.CharField(max_length=512, verbose_name="第十一题")),
                ("Question_B", models.CharField(max_length=512, verbose_name="第十二题")),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="TestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("class_num", models.IntegerField(verbose_name="班级")),
                ("result_sub", models.IntegerField(verbose_name="主观题成绩")),
                ("result_obj", models.IntegerField(verbose_name="客观题成绩")),
                (
                    "result_state",
                    models.SmallIntegerField(
                        choices=[(1, "未参加考核"), (2, "考核未通过"), (3, "考核通过")],
                        default=1,
                        verbose_name="考核结果",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("create_time", models.DateField(verbose_name="加入时间")),
                (
                    "depart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.department",
                        verbose_name="职能",
                    ),
                ),
            ],
        ),
    ]
