# Generated by Django 4.2.5 on 2023-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestStates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("class_num", models.IntegerField(verbose_name="班级")),
                ("result_sub", models.IntegerField(verbose_name="主观题成绩")),
                ("result_obj", models.IntegerField(verbose_name="客观题成绩")),
                (
                    "result_state",
                    models.SmallIntegerField(
                        choices=[(1, "未参加考核"), (2, "考核未通过"), (3, "考核通过")],
                        default=1,
                        verbose_name="考核结果",
                    ),
                ),
            ],
        ),
    ]
